### ISSUE TITLE
Multiple schemes and authentication

### ISSUE THREAD

**Issue by JustDenP** [spences10/sveltekit-vendure-commerce#387]
I'm new to graphql and svelte in general, so apologies if my questions are too obvious.

I use this repository as a training, so I would like to know if it is possible to create several api endpoints (vendure has shop-api and admin-api), and if it makes sense to use the codegen package separately, because the generation settings are more advanced there, plus, in addition to scheme.graphql, you can create scheme.ts types

Also, if your example had authorization, it would be very useful, and would make the repo a full-fledged template. Can you please tell, are you planning to add this feature? Thank you

**Comment by spences10** [comment]
Hey @JustDenP thanks for showing in interest in the project!

This is in maintenance mode really, I haven't done anything with it sonce KitQL and Houdini wnet to v1

With regard to the codegen for the endpoints I'm not really sure, for that I think you'd probably need more than one client, I've not tried this so just speculation. Maybe @jycouet can chime in on that part!

With regard to auth yeah, it would be goo to implement somthing like Lucia Auth as I'm using that on something else and it's really handy!

Maybe one day I'll come back to this, for now it's just getting the occasional dependency update until I pick it back up again.

**Comment by jycouet** [comment]
👋 hello there, 

Actually we move it here: https://github.com/vendure-ecommerce/storefront-sveltekit-starter (it's the same not up to date, but it's probably better to follow-up overthere?) Maybe @spences10 you could update this repo to point out there?

Updating the content has been on my list for sooooo long now!!! I should give 1 or 2 hours this week to update all deps at least!!! (plz push me 🥳🥳🥳)

Regarding your questions, 
- Houdini GraphQL Client supports 1 GraphQL endpoint. The idea would be to merge your 2 schemas into one and Houdini would target this one endpoint.
Fortunately, with SvelteKit, this is possible, and it's probably not too complicated to do.
```mermaid
  graph TD;
subgraph SvelteKit
      SK[frontend]-->M[GraphQL merge schema]
end
      M-->GA[ http://.../graphql]
      M-->GB[ http://.../graphql/admin]
```
I played arround in another project and it's working pretty well 👍

- With Houdini, you don't need the spearate step of "schema generation". Everything is built-in. In parallele, I'm thinking a lot about what do do with `@kitql/all-in` as I have better plans now with `remult` (separate topic)

- Auth. Lucia looks like an amazing project! But it's maybe when you own the backend as well? For vendure, you have to use their mechanism? That beeing said, I would love to have a demo with Lucia and I would love to have a full demo with vendure (and auth!)

---

What's the next step? 
Wanna build some part ? Wanna Pair ? 
Let me/us know 👍

_//Happy coding_

**Comment by JustDenP** [comment]
Thank you guys for detailed and quick response! 🫶
I was trying to understand the logic of how to point these 2 schemas to merge them later without dedicated codegen package, because Houdini points and generates only 1 schema

So do I still need to codegen 2 endpoints, merge them and then point Houdini to this file? Thank you

I'm trying to do this right for about whole day 😄
