### ISSUE TITLE
Showing <pre> on top of navbar

### ISSUE THREAD

**Issue by eustachi0** [spences10/sveltekit-vendure-commerce#64]
![image](https://user-images.githubusercontent.com/67832507/166079620-c5d26d11-a9a8-49f4-8239-7875a4a10c9e.png)

**Comment by michaelbromley** [comment]
Just a note that this was added when Scott and I were pairing on getting the cart to work - it is just there to show whether items are indeed being added to the cart. The intention is to of course replace that with an actual cart contents component.

**Comment by spences10** [comment]
Hey @eustachi0 this project hasn't been released yet, there's still a few issues I'm working through on this.

Thanks for logging this
