### ISSUE TITLE
Product page not showing properly

### ISSUE THREAD

**Issue by eustachi0** [spences10/sveltekit-vendure-commerce#65]
When open the live demo and click on a product for the first time, the product page does not show, you have to refresh to show it, then if you try to click on another product to see its product page it actually shows the page of the previous product you clicked before. Please see git below where it is more clear what I am trying to explain. It seems like is caching one product behind?

![Vendure-sveltekit-issue01](https://user-images.githubusercontent.com/67832507/166080407-2916a87b-b8ae-457d-9e70-82228b19b444.gif)
.

**Comment by spences10** [comment]
Yep, there's a lot of things still need to be fixed with this before it get released.

Thanks for the issue, they're all being worked on

**Comment by eustachi0** [comment]
Thank you! I'm looking forward to the release of this template.
